databases:
  - name: ecommercedb
    plan: free
    databaseName: ecommerce
    user: ecommerce

services:
  - type: web
    plan: free
    name: Ecommerce
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn Ecommerce.asgi:application -k uvicorn.workers.UvicornWorker"

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ecommercedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG_MODE
        value: "False"

#    volumes:
#      - name: db-volume
#        path: db.sqlite
#      - name: migrations-authentication
#        path: /applications/authentication/migrations
#      - name: migrations-product
#        path: /applications/product/migrations
#      - name: migrations-purchase
#        path: /applications/purchase/migrations