# Generated by Django 5.0.3 on 2024-03-19 14:12

import applications.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=applications.product.models.expiration, null=True),
        ),
    ]
