# Generated by Django 5.0.3 on 2024-03-20 17:37

import applications.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=applications.product.models.upload_to),
        ),
    ]
