# Generated by Django 5.0.3 on 2024-03-18 17:19

import applications.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to=applications.authentication.models.upload_to),
        ),
    ]
