# Generated by Django 5.0.3 on 2024-03-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(blank=True, upload_to='images'),
        ),
    ]
