# Generated by Django 5.0.3 on 2024-03-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_uploadedfile_description_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='card_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
